#Product Runtime Configuration File
eclipse.product=com.vendor.platform.rcp.product
osgi.splashPath=platform:/base/plugins/com.vendor.platform.rcp
osgi.bundles.defaultStartLevel=4
eclipse.application=com.vendor.platform.rcp.application
osgi.bundles=org.eclipse.equinox.simpleconfigurator@1:start
org.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info
