#ifndef EHAL_COMMON_H
#define EHAL_COMMON_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    EHAL_OK = 0,
    EHAL_ERR_PARAM = -1,
    EHAL_ERR_STATE = -2,
    EHAL_ERR_CONFIG = -3,
    EHAL_ERR_RUNTIME = -4,
    EHAL_ERR_NOT_SUPPORTED = -5,
    EHAL_ERR_BUSY = -6,
    EHAL_ERR_TIMEOUT = -7
} ehal_result_t;

typedef enum {
    EHAL_CAMERA_STAGE_NONE = 0,
    EHAL_CAMERA_STAGE_VALIDATE,
    EHAL_CAMERA_STAGE_LOAD_CONFIG,
    EHAL_CAMERA_STAGE_APPLY_VI,
    EHAL_CAMERA_STAGE_APPLY_VPSS,
    EHAL_CAMERA_STAGE_APPLY_VENC,
    EHAL_CAMERA_STAGE_INIT_HAL,
    EHAL_CAMERA_STAGE_CREATE_PIPELINE,
    EHAL_CAMERA_STAGE_CONFIGURE_VPSS,
    EHAL_CAMERA_STAGE_START_PIPELINE,
    EHAL_CAMERA_STAGE_FIRST_FRAME,
    EHAL_CAMERA_STAGE_ROLLBACK
} ehal_camera_stage_e;

#ifdef __cplusplus
}
#endif

#endif /* EHAL_COMMON_H */
